name: Build, Test, and Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'samples/**'

  pull_request:
    branches:
      - master

env:
  BUILD_CONFIGURATION: Release
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet: ['6.0.x']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Unit Test
        run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    strategy:
      fail-fast: true
      matrix:
        dotnet: ['6.0.x']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - uses: dotnet/nbgv@master
        with:
          setAllVars: true

      - name: Pack
        run: dotnet pack --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Push to feedz.io
        run: dotnet nuget push **/*.nupkg -k ${{ secrets.FEEDZ_API_KEY }} -s https://f.feedz.io/forevolve/stator/nuget/index.json
        if: github.event_name == 'pull_request'

      - name: Push to NuGet.org
        run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        if: github.event_name == 'push'
